trigger:
  branches: 
   include: [master, dev]
  paths:
   exclude: [README.md LICENSE .gitignore scripts/README.md modules/README.md conf/README.md conf/tools.list]


jobs:
- job: 'Build'
  timeoutInMinutes: 125
  cancelTimeoutInMinutes: 140
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: make docker
    displayName: 'Build docker images'
  - script: docker run build-toolchain dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Build dev toolchain'
  - script: docker run build-toolchain
    displayName: 'Build toolchain'
  - script: docker run build-base-os dev
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
    displayName: 'Build dev base-os'
  - script: docker run build-base-os
    displayName: 'Build base-os'