FROM ubuntu:latest

RUN apt-get update && apt-get install autoconf-archive curl bison g++ xz-utils libtool automake pkg-config perl libtool m4 autoconf gawk build-essential texinfo tree git sudo p7zip lzma-dev lzma wget coreutils -y && apt-get autoremove -y

COPY conf/docker/build-toolchain-entry.sh /usr/local/bin/entry.sh

RUN chmod 777 /usr/local/bin/entry.sh

RUN cd /bin/ && sudo rm sh && sudo ln -s bash sh

VOLUME /work

WORKDIR /work

ENTRYPOINT ["/usr/local/bin/entry.sh"]